### ISSUE TITLE
.fancybox-enabled persists after clicking link inside fancybox

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1413]
I have a link inside fanybox which brings me to another page. However after clicking the link the new page doesn't have a scrollbar and instead has a space where the scroll bar should be.  I think this is because the `.fancybox-enabled` class remains on the html tag. If I remove this class the scrollbar appears but that space where the scrollbar should be is also still there and the scrollbar is to the right of it. FYI I am using `.compensate-for-scrollbar` now sure if this is important for this issue.

**Comment by rrcdr** [comment]
It looks like the problem is fixed if I do something like this:

```
$('a').on('click', function() {
  $.fancybox.close();
});
```

But if I do this the close animation happens and then it goes to the new page. I would prefer if it just went to the new page without closing fancybox first. Is this possible?

**Comment by fancyapps** [comment]
Sorry, I do not understand you. Some live example would help.

**Comment by rrcdr** [comment]
@fancyapps Here is a demo. I will try to explain my problem as clearly as I can, but I don't know how to mimic linking to another page inside of Codepen.

https://codepen.io/anon/pen/GWBWep

Lets pretend the url of the demo is something like `/users/1`. Click one of the photos and fancybox pops up with a link "Check this out". Lets say the link goes to `/users/2`. Following this link will bring me to `/users/2` but the scrollbar will be hidden because the class `fancybox-enabled` still exists on the html tag.

Also, there will still be a margin to the right on this new page because the style tag with id `fancybox-noscroll` still exists. 

It looks like this is because following a link inside a fancybox instance does not trigger this chunk of code https://github.com/fancyapps/fancybox/blob/8acf7b71a46eea79bcc952cf96a0677c69a578cd/src/js/core.js#L2122.

Please let me know if I can clarify anything.

**Comment by fancyapps** [comment]
The confusing part is this - "Following this link will bring me to /users/2 but the scrollbar will be hidden because the class fancybox-enabled still exists on the html tag".

What do you mean by that? If you would click a link leading another page, then browser would reload the page and there would be no fancybox at all. Of course, if your url would contain some #hash, then fancybox would try to open new instance from that.

**Comment by rrcdr** [comment]
Hmm, maybe it's because I'm using turbolinks.

**Comment by fancyapps** [comment]
In that case, maybe try to add `data-turbolinks="false"` to your links inside fancybox.

**Comment by rrcdr** [comment]
That doesn't seem to work unfortunately, I wonder what the issue is.
