### ISSUE TITLE
Custom small close button

### ISSUE THREAD

**Issue by MattPostlethwaite** [fancyapps/fancybox#1417]
After adding a custom small close button (using "closeTpl")  I noticed that without the ".fancybox-close-small" class it wasn't being removed when closing and a new one was being added every time the modal is opened.

However, adding this class adds styling to the custom button from fancybox.css which has to then be overwritten.

The following is how the button is currently being removed.

```
if ( slide.opts.smallBtn === true ) {
  slide.$content.find( '.fancybox-close-small' ).remove().end().eq(0).append( slide.opts.closeTpl );
}
```
https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L1790

It might be better to target the "data-fancybox-close" attribute rather than the class? or have another class with doesn't add any styling to the custom close button

**Comment by fancyapps** [comment]
Hi,

Thanks. The latest commit to v3.1 branch should fix this - https://github.com/fancyapps/fancybox/tree/3.1

**Comment by seabasss** [comment]
@fancyapps I updated and the small button popped up everywhere now. How do I remove it? smallBtn : false didn't work. CSS the way?

**Comment by fancyapps** [comment]
@seabasss `smallBtn:false` should do the job - http://codepen.io/fancyapps/pen/NjXbXw?editors=1100

**Comment by seabasss** [comment]
@fancyapps Can I still plave it in the code. It still shows up for me...

```
	$("[data-fancybox]").fancybox({
		speed : 330,
		animationDuration : 330,
		loop : false,
		opacity : 'auto',
		margin : [0, 0],
		gutter : 30,
		infobar : false,
		toolbar : false,
		slideShow  : false,
		fullScreen : false,
		thumbs     : false,
		closeBtn   : false,
		autoFocus  : false,
		smallBtn : false,
		clickOutside : false,
		touch : false,
		keyboard : false,
		beforeLoad: function( instance, slide ) {
			$('#powerTip').hide();
		},
		beforeClose: function( instance, slide) {
			$(this).disposeVideo();
		}
	});
```

**Comment by MattPostlethwaite** [comment]
Hi @fancyapps,

When using the CDN version 3.0.47 I get this:

<img width="650" alt="screen shot 2017-05-09 at 09 39 49" src="https://cloud.githubusercontent.com/assets/7222344/25842378/c3db413e-349b-11e7-8b07-18cc73516c0c.png">

But with the version 3.1.2 from 3.1 branch I get this:

<img width="650" alt="screen shot 2017-05-09 at 09 40 12" src="https://cloud.githubusercontent.com/assets/7222344/25842424/e9fe0202-349b-11e7-9579-c0987a9e997a.png">

As you can see 3.1.2 now shows no smallBtn but instead shows the larger frame.

**Comment by fancyapps** [comment]
@MattPostlethwaite  Sorry, but comments like this are completely useless, I do not know how to reproduce this, everything works fine for me.

**Comment by MattPostlethwaite** [comment]
That's fine, I just wanted to highlight another possible issue that this change may have produced.

However, after further investigation, I have found that the issues was that I was using:
```
$('.modal-trigger').fancybox({
  closeTpl : '<div data-fancybox-close class="fancybox-close-small modal-close">Button</div>'
});
```

Which in version 3.1.2 needs to be:
```
$('.modal-trigger').fancybox({
  btnTpl : {
    smallBtn : '<div data-fancybox-close class="fancybox-close-small modal-close">Button</div>'
  }
});
```

Thought I'd best comment this incase someone find this issue in the future.

**Comment by fancyapps** [comment]
Thanks, I`m glad you sorted this out.
